#!/usr/bin/env python3
"""Assemble per-shot prompt cards from character DNA blocks + shots.json.

Usage: python3 scripts/build_prompts.py projects/magnificent-failure-five

Reads  <proj>/characters/*.md   (last ```prompt fenced block per file)
       <proj>/prompts/shots.json
Writes <proj>/prompts/<shot_id>.md  (overwrites; cards are generated artifacts)
"""
import json
import pathlib
import re
import sys

FENCE = re.compile(r"```prompt\n(.*?)```", re.S)


def load_block(path: pathlib.Path) -> str:
    blocks = FENCE.findall(path.read_text())
    if not blocks:
        sys.exit(f"error: no ```prompt block in {path}")
    return blocks[-1].strip()


def main() -> None:
    proj = pathlib.Path(sys.argv[1])
    chars_dir = proj / "characters"
    data = json.loads((proj / "prompts" / "shots.json").read_text())
    style = load_block(chars_dir / f"{data['style']}.md")

    total = sum(s["len"] for s in data["shots"])
    if not 28 <= total <= 32:
        sys.exit(f"error: shot lengths sum to {total}s, expected ~30s")

    for shot in data["shots"]:
        dna = [load_block(chars_dir / f"{c}.md") for c in shot["chars"]]
        refs = "all five" if len(shot["chars"]) == 5 else ", ".join(shot["chars"])
        card = f"""# {shot['id']} — {shot['title']} ({shot['len']}s, {shot['framing']})

> GENERATED by scripts/build_prompts.py — edit characters/*.md or prompts/shots.json, not this file.

**Workflow:** `wf2_shot_r2v.json` · **refs:** {refs} · **length:** {shot['len']}s
**Seed:** take N → {shot['seed_base']} + N (log every take in `take-log.md`)
**Narrator (post):** {shot['narrator']}
**Fallback:** 3 failed takes → `wf3a_keyframe.json` + `wf3b_i2v.json` (fix the input, not the seed)

## Copy-paste prompt

{style}

Characters:
{chr(10).join(f'- {d}' for d in dna)}

Action: {shot['motion']}

Audio: {shot['audio']}
"""
        (proj / "prompts" / f"{shot['id']}.md").write_text(card)
        print(f"wrote prompts/{shot['id']}.md ({len(shot['chars'])} chars)")


if __name__ == "__main__":
    main()
